---
title: "TGAV for all CMIP6 models"
author: "ACS"
date: "2/14/2020"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(RColorBrewer)


knitr::opts_chunk$set(echo = FALSE)
```

# Set up

In the process of learning the patterns relating $\Delta TOS_{local}(t) = a Tgav(t) + b$ for each ESM, the time series of Tgav for each ESM is calculated (from monthly gridded `tas` data) and saved. Here, we plot all for comparison.


```{r load}

# List of all tgav file names
tgavfiles <- list.files('tgavs', full.names = TRUE)
tgavfiles <- tgavfiles[!(grepl('monthly', tgavfiles))]


# Read in and shape each tgav file, results in a list
# each entry correspondig to one ESM
modeltgavs <- lapply(tgavfiles, function(filename){
  
  if(grepl('CAMS', filename)){
    
    modelyears <- 2015:2099
    
  } else {
    
    modelyears <- 2015:2100

  }

    tibble(tgav = readRDS(filename),
         year = modelyears) %>%
      mutate(model = substr(filename, 19, nchar(filename) - 11)) ->
      x
    
  return(x)
  
})

# Combine all of the lists together into a single table
tgav_data <- do.call(rbind, modeltgavs)


# Plot the time series and save
p <- ggplot(tgav_data, aes(x = year, y = tgav, color = model)) +
  geom_line() +
  theme_bw()

ggsave('figures/allmodels_tgav.png', p, width = 6, height = 6, units = 'in')


# Save a csv of all of the tgav data together
write.csv(tgav_data, 'tgavs/allmodels_tgavdata.csv', row.names = F)


# Arrange models from hottest to coldest based on temperature
# in some year. Save the ordered list.
tgav_data %>%
  filter(year == 2100) %>%
  mutate_if(., is.numeric, as.numeric) %>%
  arrange(desc(tgav)) %>%
  write.csv(., 'models_ordered_hottest_to_coldest/orderedmodels_2100.csv', row.names = F)




tgav_data %>%
  filter(year == 2099) %>%
  mutate_if(., is.numeric, as.numeric) %>%
  arrange(desc(tgav)) %>%
  write.csv(., 'models_ordered_hottest_to_coldest/orderedmodels_2099.csv', row.names = F)



tgav_data %>%
  filter(year == 2015) %>%
  mutate_if(., is.numeric, as.numeric) %>%
  arrange(desc(tgav)) %>%
  write.csv(., 'models_ordered_hottest_to_coldest/orderedmodels_2015.csv', row.names = F)

```

